---
- name: Install HaProxy
  hosts: haproxy
  become: yes
  tasks:
    - name: hostname setings
      command: hostnamectl set-hostname {{ item.new_hostname }}
      when: inventory_hostname == item.inventory_hostname
      loop:
        - { inventory_hostname: 'haproxy', new_hostname: 'haproxy' }

    - name: Setings /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        create: yes
      with_items:
        - 10.236.0.170 master1
        - 10.236.0.172 master2
        - 10.236.0.173 work1
        - 10.236.0.174 work2
        - 10.236.0.175 haproxy

    - name: Add parametry /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - vm.swappiness = 10
        - net.core.somaxconn = 16384
        - net.core.netdev_max_backlog = 2000
        - net.core.netdev_budget = 1000
        - net.core.default_qdisc = fq
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1
        - net.ipv4.tcp_mtu_probing = 0
        - net.ipv4.tcp_window_scaling = 1
        - net.ipv4.tcp_congestion_control = bbr
        - net.ipv4.tcp_notsent_lowat = 16384
        - net.ipv4.tcp_timestamps = 1
        - net.ipv4.tcp_sack = 1
        - net.ipv4.tcp_tw_reuse = 1
        - net.ipv4.tcp_adv_win_scale = -2
        - net.ipv4.tcp_syncookies = 0
        - net.ipv4.tcp_max_syn_backlog = 4096
        - net.ipv4.tcp_synack_retries = 1
        - net.ipv4.tcp_max_orphans = 65536
        - net.ipv4.tcp_fin_timeout = 10
        - net.ipv4.tcp_keepalive_time = 60
        - net.ipv4.tcp_keepalive_intvl = 15
        - net.ipv4.tcp_keepalive_probes = 5
        - net.ipv4.tcp_slow_start_after_idle = 0
        - net.ipv4.conf.all.accept_source_route = 0
        - net.ipv4.conf.all.accept_redirects = 0
        - net.ipv4.conf.all.secure_redirects = 0
        - net.ipv4.conf.all.send_redirects = 0
        - net.ipv4.icmp_echo_ignore_broadcasts = 1
        - net.ipv4.icmp_ignore_bogus_error_responses = 1
        - net.core.rmem_max = 56623104
        - net.core.wmem_max = 56623104
        - net.core.rmem_default = 56623104
        - net.core.wmem_default = 56623104
        - net.core.optmem_max = 40960
        - net.ipv4.tcp_rmem = 4096 87380 56623104
        - net.ipv4.tcp_wmem = 4096 65536 56623104
        - net.ipv6.conf.lo.disable_ipv6 = 1

    - name: Apply sysctl
      command: sysctl -p


    - name: Off /etc/apt/apt.conf.d/20auto-upgrades
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "0";
          APT::Periodic::Unattended-Upgrade "0";
        owner: root
        group: root
        mode: '0644'

    - name: Installing auxiliary packages
      shell: apt install -y curl wget gnupg iptables tmux keepalived haproxy ca-certificates apt-transport-https
      ignore_errors: yes


